name: Node.js CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present

    # Bước sign APK/AAB và upload lên Google Play
    - name: Sign APK
      run: |
        echo ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode > my-release-key.keystore
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore my-release-key.keystore \
          -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }} \
          -signedjar app/build/outputs/apk/release/app-release.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ secrets.ANDROID_KEY_ALIAS }}
    
    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
        packageName: com.yourapp.package
        releaseFiles: app/build/outputs/apk/release/app-release.apk
        track: production  # Hoặc bạn có thể chọn "beta" hoặc "alpha" tùy thuộc vào môi trường bạn muốn deploy
