name: React Native CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'yarn'
    - run: yarn install

    # Set up Android SDK
    - name: Set up Android SDK
      uses: reactivecircus/android-emulator-runner@v3
      with:
        api-levels: 30
        arch: x86_64
        target: google_apis
        force-avd-creation: true

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk

  # Optional: Add a job for iOS if needed
  build-ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'yarn'
    - run: yarn install

    # Install dependencies
    - name: Install dependencies
      run: |
        cd ios
        pod install

    - name: Build iOS
      run: |
        xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -configuration Release -sdk iphoneos -archivePath $PWD/build/MyApp.xcarchive archive
        xcodebuild -exportArchive -archivePath $PWD/build/MyApp.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $PWD/build

    - name: Upload iOS IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-release-ipa
        path: build/*.ipa
