name: React Native CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Set up Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Dependencies
      run: yarn install

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-levels: 33
        build-tools: 33.0.0
        components: |
          emulator
          platform-tools
          platforms;android-33

    - name: Grant Execution Permissions for gradlew
      run: chmod +x android/gradlew

    - name: Update Gradle Wrapper
      run: |
        cd android
        ./gradlew wrapper --gradle-version 7.5.1 --no-daemon

    - name: Clean Gradle Build
      run: |
        cd android
        ./gradlew clean --no-daemon

    - name: Refresh Gradle Dependencies
      run: |
        cd android
        ./gradlew --refresh-dependencies --no-daemon

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon --warning-mode=all --stacktrace --info

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
