name: React Native CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'yarn'

    # Set up Java JDK 17
    - name: Set up Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Install dependencies
    - run: yarn install

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-levels: 33
        build-tools: 33.0.0
        ndk: 21.4.7075529
        components: |
          emulator
          platform-tools
          platforms;android-33
          system-images;android-33;google_apis;x86_64

    # Grant execution permissions for gradlew
    - name: Grant execution permissions for gradlew
      run: chmod +x android/gradlew

    # Clean Gradle Build
    - name: Clean Gradle Build
      run: |
        cd android
        ./gradlew clean

    # Refresh Gradle dependencies
    - name: Refresh Dependencies
      run: |
        cd android
        ./gradlew --refresh-dependencies

    # Build APK
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace --info

    # Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
